# Generated by Django 2.1 on 2018-10-01 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interestrateswap',
            name='assetType',
            field=models.CharField(default='interstRateSwap', max_length=100),
        ),
    ]
