# Generated by Django 2.1 on 2018-10-01 05:08

from django.db import migrations, models
import interest.models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_auto_20181001_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='consortiumPacket',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='municipalPacket',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='consortium',
            field=models.CharField(blank=True, choices=[('someConsortiumHashId', 'Global Interest Rate Swap Group'), ('index', 'Weighted Index Consortium')], max_length=255),
        ),
        migrations.AddField(
            model_name='transaction',
            name='consortiumPacketHash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='transaction',
            name='municipalPacketHash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='asset',
            name='validThrough',
            field=models.DateTimeField(default=interest.models.default_end_time),
        ),
    ]
