# Generated by Django 2.1 on 2018-09-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0002_auto_20180905_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='registrar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='confirmations',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
