# Generated by Django 2.1.2 on 2018-10-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('interest', '0003_auto_20181001_0508'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='interestrateswap',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AddField(
            model_name='asset',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_interest.asset_set+', to='contenttypes.ContentType'),
        ),
    ]
