# Generated by Django 2.1 on 2018-09-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0003_auto_20180905_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=10, max_digits=40),
        ),
    ]
