# Generated by Django 2.1.2 on 2018-10-11 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0004_auto_20181010_1645'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interestrateswap',
            name='asset_ptr',
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={},
        ),
        migrations.RemoveField(
            model_name='asset',
            name='polymorphic_ctype',
        ),
        migrations.DeleteModel(
            name='InterestRateSwap',
        ),
    ]
