# Generated by Django 2.1 on 2018-09-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0005_auto_20180907_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='registrationAsset',
        ),
        migrations.AddField(
            model_name='transaction',
            name='standardAsset',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='interest.Asset'),
        ),
    ]
