# Generated by Django 2.1 on 2018-09-29 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0006_auto_20180917_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='consortiumPacket',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='municipalPacket',
            field=models.TextField(blank=True),
        ),
    ]
