# Generated by Django 2.1.2 on 2018-10-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0006_auto_20181011_0842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['timestamp']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='sender',
            field=models.CharField(max_length=255),
        ),
    ]
