# Generated by Django 2.1.2 on 2018-10-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interest', '0007_auto_20181011_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='transaction',
            name='validThrough',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
